### ISSUE TITLE
Don't include versions that aren't releases, e.g. wheel  0.30.0a0

### ISSUE THREAD

**Issue by drnic** [cf-platform-eng/concourse-pypi-resource#6]
https://ci.starkandwayne.com/teams/main/pipelines/sample-python-flask-app-boshrelease/jobs/wheel/builds/2

"Version 0.30.0a0 is not a release; skipping download"

Is it possible to avoid having these alpha releases included?

**Comment by drnic** [comment]
Interestingly, `0.30.0` has been released, `0.30.0a0` is no longer on https://pypi.python.org/pypi/wheel, but the error in this resource persists (I destroyed the pipeline and rebuilt it too)

**Comment by mboldt** [comment]
The PyPI JSON API that this code uses (https://pypi.python.org/pypi/wheel/json) does still contain the `0.30.0a0` release. This is still bad behavior because (1) presumably that release is an alpha and `0.30.0` is the GA, and (2) it's not helpful to just not download a release.

Since `get` only wants to deal with real releases, should add a filter here in check to only consider them: https://github.com/cf-platform-eng/concourse-pypi-resource/blob/master/pypi_resource/check.py#L33

If all goes well, I can take a crack at that this week.

**Comment by mboldt** [comment]
The resource now consistently filters out these dev releases. If you or someone comes up with a use case where the dev releases are desired, we can make that filter optional (e.g., via a param on `get`).
